//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBCenter.CBCenterBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillTransaction()
        {
            this.BookTransactions = new HashSet<BookTransaction>();
        }
    
        public int TransactionID { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> SchoolsId { get; set; }
        public string BillTransactionNumber { get; set; }
    
        public virtual SchoolMaster SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTransaction> BookTransactions { get; set; }
        public virtual SchoolsMaster SchoolsMaster { get; set; }
    }
}
