//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBCenter.CBCenterBL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CBCenterDBEntities : DbContext
    {
        public CBCenterDBEntities()
            : base("name=CBCenterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMaster> BookMasters { get; set; }
        public virtual DbSet<SellBookTransaction> SellBookTransactions { get; set; }
        public virtual DbSet<SellCustoemrRecord> SellCustoemrRecords { get; set; }
        public virtual DbSet<BillTransaction> BillTransactions { get; set; }
        public virtual DbSet<BookTransaction> BookTransactions { get; set; }
        public virtual DbSet<SchoolMaster> SchoolMasters { get; set; }
        public virtual DbSet<SchoolsMaster> SchoolsMasters { get; set; }
        public virtual DbSet<ReceivePayment> ReceivePayments { get; set; }
    
        public virtual ObjectResult<Sp_GetPreviousOrderDetails_Result> Sp_GetPreviousOrderDetails(Nullable<int> schoolId)
        {
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetPreviousOrderDetails_Result>("Sp_GetPreviousOrderDetails", schoolIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetAllOrderDetails_Result> Sp_GetAllOrderDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetAllOrderDetails_Result>("Sp_GetAllOrderDetails");
        }
    }
}
