//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBCenter.CBCenterBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivePayment
    {
        public int PaymentId { get; set; }
        public Nullable<int> SchoolsId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> SystemReciveDate { get; set; }
        public Nullable<int> Mode { get; set; }
        public string BillTransactionNumber { get; set; }
    
        public virtual SchoolsMaster SchoolsMaster { get; set; }
    }
}
