//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBCenter.CBCenterBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellBookTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string TotalDiscount { get; set; }
    
        public virtual BookMaster BookMaster { get; set; }
        public virtual SellCustoemrRecord SellCustoemrRecord { get; set; }
    }
}
